- name: Cache Node.js modules
  uses: actions/cache@v3
  with:
    path: ~/.npm
    key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}-v2
    restore-keys: |
      ${{ runner.OS }}-node-
