name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          rimraf build && mkdirp build
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='.github' . build/
          touch build/.nojekyll

      - name: List build directory contents (optional)
        run: ls -la ./build  # This step is optional

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build

  deploy:
    needs: build  # This job depends on the build job completing
    runs-on: ubuntu-latest
   
